### PR TITLE
added creole for languages, commented out other languages

### PR DESCRIPTION
**Pull request by davidflores2**

### CODE REVIEW

**Comment by ErnieAtLYD** [comment]
Code change looks good to me!

**Comment by eddroid** [comment]
Sorry for taking so long to merge this change. Thank you for your contribution!

**Comment by eddroid** [comment]
This change has been deployed: https://ed-miami-ohana-web-search.herokuapp.com/

**Comment by eddroid** [comment]
Renamed app to https://miami-ohana-web-search.herokuapp.com/

**Pull request merged**
